### ISSUE TITLE
cost-benefit of integrating `tidygraph`+`sfnetworks` functions?

### ISSUE THREAD

**Issue by daauerbach** [pet221/SSNbler#3]
I'm pleased to find this very nicely documented package and still just digging into it, so I want to underscore that this is truly an open ended question not a critique of any sort! I've found [`sfnetworks`](https://github.com/luukvdmeer/sfnetworks) and the underlying [`tidygraph`](https://github.com/thomasp85/tidygraph) to be fast and convenient for some tasks related to the processing in `lines_to_lsn` and perhaps other functions like `updist_edges`. I understand the tradeoffs of creating additional dependencies vs staying self-contained, but I'm curious if those were a consideration and decided against? For example, the little snippet below (clipped from a larger function) trims a LINESTRING object down to an AOI and then adds a few spatial attributes. I'm wondering about this as I'm scoping the construction of workflows around `SSNbler`+`SSN2`, particularly over larger domains/networks. (And, this is a separate issue, but I'll ask here for now: any thought to storing/serving a data-library of pre-prepared .gpkgs for widely used hydrography such as NHDplus?)

```
  l <- lines_3dhp |>  #global object from an st_read and st_cast of a flowline .gdb
    filter(comid == cat) |> 
    select(uid = UniqueID, shape_length = SHAPE_Length, comid, desc = Desc, zslope_est, zmax) |> 
    sfnetworks::as_sfnetwork() |>
    tidygraph::activate(nodes) |>
    tidygraph::convert(
      tidygraph::to_largest_component,
      .clean = T #this drops the .tidygraph_node_index/edge_index that no longer apply & are potentially confusing
    ) |>
    mutate(
      idn = seq_along(SHAPE),
      #raindrop perspective paths from nodes to root
      d_root = tidygraph::node_distance_to(tidygraph::node_is_root()),
      d_root_ft = tidygraph::node_distance_to(tidygraph::node_is_root(), weights = shape_length),
      d_root_km = 0.0003 * d_root_ft,
      #looking 'up' perspective to perimeter from per-node 'me'
      in_n = tidygraph::local_size(order = nrow(tidygraph::.N()), mode = "in")
    )
```

**Comment by pet221** [comment]
@daauerbach Thanks! 

The National Stream Internet ([NSI](https://research.fs.usda.gov/rmrs/projects/national-stream-internet)) dataset is a pre-prepared library of pre-processed streams and prediction points, which is based on NHDPlus V2 medium resolution data. They’re in shapefile rather than GeoPackage format, but that shouldn’t cause any issues in sf, SSNbler or SSN2. You’ll still need to process the data using SSNbler, but most of the topological errors and topological restrictions have been fixed thanks to the folks at the USFS. 

We did briefly look at sfnetworks and tidygraph when we were designing the SSN data structure and thinking about processing spatial networks in SSNbler. They both look like useful packages, but we already have dependencies on sf and igraph and wanted to keep the number of package dependencies as low as possible. However, it probably makes sense to use of the functionality of sfnetworks and tidygraph in your own workflows, assuming that you can easily convert to/from the sf objects we use in SSNbler. 

Out of curiousity, what advantages do you see in including dependencies on sfnetworks and tidygraph? Is it just more concise/clean R code? Or do you think there are other benefits (e.g. computational, additional functionality, etc)?

**Comment by daauerbach** [comment]
No, thank you!! NSI is exactly my conceptual model as I contemplate exciting possibilities with 3DHP.

I was asking mostly from the perspective of whether you'd seen something that prompted intentional avoidance - which it doesn't seem is the case. I came to those packages and SNNbler after a long time away from working with igraph, and they seemed nicely put together, but I was curious for the views of a team that's expert and active in this area. 

I imagine we agree that clean/concise code _is_ important to the extent that it eases maintenance, but your and @michaeldumelle highly readable functions here already easily check that box, so unlikely worth refactoring effort, especially for things that are mostly likely run once or a few times at the outset of projects. I haven't done any careful benchmarking to see how that `tidygraph::node_distance_to(tidygraph::node_is_root(), weights = shape_length)` (on a edges-as-nodes graph) compares to `updist_edges` or something like `tidygraph::map_local_dbl` with `mode = "in"` compares to `afv_edges`. I don't anticipate it, but if I notice something substantive and worth anyone's time, then I'll mention it here.

**Comment by daauerbach** [comment]
Minor addendum: After a (little) bit more time, I wanted to offer a further compliment that this is a very nice toolset. I'm still getting familiar, but this little snippet was handy in the course of building up a model to quickly see topological errors. I used it to make a little vector of edges-to-drop manually, and I appreciate the "know your data" value of manual inspection, but I may end up writing some logic to programmatically iteratively clean (e.g., auto-dropping the shortest edge from a 'complex convergence' or divergence/split path or subsetting to the outlet of the largest component). Definitely interested in hearing any thoughts re: why you'd advise against that.

Anyway - awesome to be able to quickly get to thinking about the river science and not spend forever fussing with the hydrography prep. Thanks again for all the work put in that's making my life better!

```
mapview::mapview(list(
  flw = sf::st_read(file.path(dir_ssn, "edges.gpkg")),
  nod = sf::st_read(file.path(dir_ssn, "nodes.gpkg")),
  err = sf::st_read(file.path(dir_ssn, "node_errors.gpkg")) #|> as_tibble() |> count(nodecat, error)
  ), zcol = c("dasqkm_tot","nodecat","error"))
```

**Comment by pet221** [comment]
@daauerbach I understand the desire to automatically clean topological errors - especially in large datasets, but keep in mind that it comes with a risk. Automatically dropping the shortest edge could artificially disconnect significant portions of the network, which could have negative consequences in the modelling and prediction. Tail-up and tail-down covariance models have no correlation between observed and/or prediction sites located on separate networks.

**Comment by daauerbach** [comment]
Absolutely! After implementing a little logic to 'auto-clean' along the lines of what I described above, and then doing some comparisons and inspections (with my NHDplusHR basins), I'm that much more convinced that, for better or worse, a 'semi-auto' workflow is likely to be the most robust. With your functions and a tweaked version of that `mapview` flow, it's really easy to narrow in on the problems and avoid isolating subgraphs (or just picking the wrong edge to drop for other reasons). 

I haven't gone back to testing this with 3DHP, but I am curious how it'll play with linework that's already quite topologically 'clean'. Even then, it seems like there'll still need to be some judgement call on valid, real-world split-paths/divergences.

**Comment by michaeldumelle** [comment]
@daauerbach keep us updated on your testing with 3DHP!
